### ISSUE TITLE
Cannot find mean annotation for junior and senior.

### ISSUE THREAD

**Issue by ishuowang** [christianpayer/MedicalDataAugmentationTool-HeatmapUncertainty#1]
I notice there are three `.csv` file in folder of `setup_ann/all_landmarks`, which are `all_challenge.csv`, 'all_junior.csv' and `all_senior.csv`. I compare the `all_challenge.csv` file with `all_senior.csv` and found that they have the same value.
below shows the first three line on each file.
```
# all_challenge.csv
001,83.5,99.6,147.3,102.9,128.9,127.9,60.4,122.8,137.5,165.4,138.6,201.9,133.3,220,126.3,227.2,130.5,225.2,69.4,180.5,146,187,145,186.4,158.8,175.3,156.9,201.3,151.4,162,138.2,231,94.4,150.6,143.6,156.9,66.4,134
002,81,105.2,139.5,98.5,128.1,123.8,60.2,125.8,139.3,158.8,134.9,185.6,138.1,200.5,132,209.1,136.3,206.3,68.7,175.6,140.7,171.8,142.6,173.4,151.9,166.9,151.2,183.5,146.2,151.5,145.9,210.3,97.8,143.3,139.9,144.5,64.3,135.3
003,76.1,110.5,132.9,91.1,125,118.1,62.2,127.9,143.6,141.5,143.9,174.4,146,188.2,140.6,193.5,144.8,192,81.5,171,145.1,157.5,149.5,160.8,158.1,144.9,159.6,168.7,152.4,136.9,152.6,192.3,100.8,140.4,142,135,71.2,134.8

# all_senior.csv
001,83.5,99.6,147.3,102.9,128.9,127.9,60.4,122.8,137.5,165.4,138.6,201.9,133.3,220,126.3,227.2,130.5,225.2,69.4,180.5,146,187,145,186.4,158.8,175.3,156.9,201.3,151.4,162,138.2,231,94.4,150.6,143.6,156.9,66.4,134
002,81,105.2,139.5,98.5,128.1,123.8,60.2,125.8,139.3,158.8,134.9,185.6,138.1,200.5,132,209.1,136.3,206.3,68.7,175.6,140.7,171.8,142.6,173.4,151.9,166.9,151.2,183.5,146.2,151.5,145.9,210.3,97.8,143.3,139.9,144.5,64.3,135.3
003,76.1,110.5,132.9,91.1,125,118.1,62.2,127.9,143.6,141.5,143.9,174.4,146,188.2,140.6,193.5,144.8,192,81.5,171,145.1,157.5,149.5,160.8,158.1,144.9,159.6,168.7,152.4,136.9,152.6,192.3,100.8,140.4,142,135,71.2,134.8
```

But the ISBI2015 cephalometric challenge said that they use the mean location of senior and junior as the ground truth. Should I create the `all_challenge.csv` with the mean location of senior and junior and replace the origin one?

**Comment by franzthaler** [comment]
The two .csv files `all_challenge.csv` and `all_senior.csv` are very similar but not the same. The file `all_challenge.csv` contains the landmark definitions as they were originally defined in the challenge. However, due to a systematic shift in some of the annotations of two landmarks, these were corrected later on, see, e.g., line 301 where they are not exactly the same:
```
# all_challenge.csv
301,73.4,94.5,130.5,91.3,122.8,111.6,54.3,114.2,134.6,140.7,131,180.3,131.2,189.5,126.2,196,129.5,193.7,65.6,169.2,140.3,160.7,141.7,160.9,152.2,148.6,149.6,175.1,146.8,139.6,138.4,197.1,91,134.6,135.5,135.8,60.5,122

# all_senior.csv
301,73.4,94.5,130.5,91.3,122.8,111.6,54.3,114.2,134.6,140.7,131,180.3,131.2,189.5,126.2,196,129.5,193.7,65.6,169.2,140.3,160.7,141.7,160.9,152.2,148.6,149.6,175.1,146.8,139.6,144,186.3,91,134.6,135.5,135.8,60.5,122
```
You can find more information on this in our paper [**Modeling Annotation Uncertainty with Gaussian Heatmaps in Landmark Localization**](https://www.melba-journal.org/papers/2021:014.html) and some papers we cited.

Generally, I would recommend to either use only the `all_junior.csv` annotations as they are more consistent, i.e., no systematic shift occured, or to use the mean of `all_junior.csv` and `all_senior.csv`, where annotations are corrected. For evaluation and comparison to other methods, however, you have to be careful as some other methods used the old annotations of `all_challenge.csv`. You can check Table 2 of our paper to get some overview on how different related work evaluated their method on this dataset.

**Comment by ishuowang** [comment]
Thank you solve my confusion! You save a lot of my life!
