### ISSUE TITLE
Where can I find the report for test1 and test2 dataset separately?

### ISSUE THREAD

**Issue by ishuowang** [christianpayer/MedicalDataAugmentationTool-HeatmapUncertainty#2]
After I ran `python main.py` and produce some report files like`/allLms/all/sameFalse_sigma5.0/2022-04-19_04-18-43/iter_40000/mean_eval.txt`

I open the report file and found that report is for test1+test2(250 images, 4750 landmarks)
```
PE (4750 out of 4750 valid gt; 4750 valid pred):
mean:   1.244
std:    1.236
median: 0.885
IPE:
mean:   1.244
std:    0.341
median: 1.190
#outliers >= 2: 841 (17.705%)
#outliers >= 2.5: 532 (11.200%)
#outliers >= 3: 338 (7.116%)
#outliers >= 4: 145 (3.053%)
#outliers >= 10: 6 (0.126%)
#outliers >= 20: 0 (0.000%)
```

My question is how can I get the report for test1 and test2 separately?

Another question is in such report, it shows the SDR(which is outliers) in 2mm, 2.5mm, 3mm ..., so what is the corresponding ground truth for the report? is it the annotation store in the `all_challenges.csv` file?

**Comment by franzthaler** [comment]
> My question is how can I get the report for test1 and test2 separately?

The current implementation in the repository unfortunately does not support a separate evaluation as is. The test set for evaluation is defined in `melba_cep/dataset.py` in the following line as `'test_all.txt'` which contains all 250 image ids.

```
...
self.val_id_list_file_name = os.path.join(self.setup_base_folder, 'test_all.txt')
...
```

A simple work-around solution would be to simply modify `test_all.txt` to `test1.txt` or `test2.txt` respectively and train a new model. There are obviously better solutions, however, some modifications to the code would be required.

On one hand, you could load a trained model and evaluate it on one test set after the other. To do so, in `melba_cep/main.py`, you can define the member `self.load_model_filename` of `MainLoop` in its `__init__` method by setting the path to the respective saved model in the `weights` folder of your trained model:

```
def __init__(...):
    ...
    self.load_model_filename = 'PATH_TO_EXPERIMENT/2021-07-16_10-39-39/weights/model-40000'
    ...
```
Additionally, in `melba_cep/main.py`, instead of calling `loop.run()` call `loop.run_test()`. Finally, replace `test_all.txt` by `test1.txt` or `test2.txt` as described above.

If you prefer to obtain the results for all test sets during training directly, you could, e.g., initialize multiple `Dataset` objects in `melba_cep/main.py` which should look something like this:

```
...
dataset = Dataset(**dataset_parameters, test_file_to_use='test_all.txt')
self.dataset_train = dataset.dataset_train()
self.dataset_val = dataset.dataset_val()

dataset_test1 = Dataset(**dataset_parameters, test_file_to_use='test1.txt')
self.dataset_test1_val = dataset_test1.dataset_val()

dataset_test2 = Dataset(**dataset_parameters, test_file_to_use='test2.txt')
self.dataset_test2_val = dataset_test2.dataset_val()
...
```
In this case, it would be necessary to modify the method `test()` in `melba_cep/main.py` such that the evaluation is performed on all objects. It also might be necessary to modify some file output names such that files are not overwritten.

> Another question is in such report, it shows the SDR(which is outliers) in 2mm, 2.5mm, 3mm ..., so what is the corresponding ground truth for the report? is it the annotation store in the all_challenges.csv file?

In `melba_cep/main.py` the variable `landmark_sources` is defined as a list of one or multiple landmark annotator shorthands, e.g. as:
`landmark_sources = ['junior']`
or
`landmark_sources = ['junior', 'senior', 'ann1', 'ann2', 'ann3', 'ann4', 'ann5', 'ann6', 'ann7', 'ann8', 'ann9']`

The ground truth used for evaluation of the SDR is computed as the mean of the landmarks from the annotators defined in the list.

**Comment by ishuowang** [comment]
Thanks for your reply!
